version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:5432"

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      NODE_ENV: ${NODE_ENV}
    ports:
      - "${BACKEND_PORT}:3000"
    depends_on:
      - postgres
    volumes:
      - ./uploads:/app/uploads

  frontend:
    build:
      context: ./blog-frontend
      dockerfile: Dockerfile
    ports:
      - "${FRONTEND_PORT}:5173"
    environment:
      VITE_API_URL: ${VITE_API_URL}
    depends_on:
      - backend

volumes:
  postgres_data: