services:
  - type: web
    name: blog-backend
    env: node
    buildCommand: npm install --legacy-peer-deps && npm run build
    startCommand: npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: DB_HOST
        fromService:
          type: postgres
          name: blog-db
          property: host
      - key: DB_PORT
        fromService:
          type: postgres
          name: blog-db
          property: port
      - key: DB_USERNAME 
        fromService:
          type: postgres
          name: blog-db
          property: user
      - key: DB_PASSWORD
        fromService:
          type: postgres
          name: blog-db
          property: password
      - key: DB_NAME
        fromService:
          type: postgres
          name: blog-db
          property: database